sudo: required
services:
  - docker

before_install:
  - docker build -t isurendra77/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run isurendra77/react-test npm test -- --coverage

after_success:
  - docker build -t isurendra77/multi-client ./client
  - docker build -t isurendra77/multi-nginx ./nginx
  - docker build -t isurendra77/multi-server ./server
  - docker build -t isurendra77/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ikalpana82/multi-client
  - docker push ikalpana82/multi-nginx
  - docker push ikalpana82/multi-server
  - docker push ikalpana82/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2 
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-306476627547
  bucket_path: multi-docker 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
